config/routes.rb
Rails.application.routes.draw do
  get 'projects/dashboard'
  get 'projects/new'
  post '/projects',  to: 'projects#create'
  get 'projects/dashboard/:filter_by', to: 'projects#dashboard', as: "list_filtered"

  root 'projects#dashboard'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
validates_presence_of :name, :description, :begin, :end, :state

    enum state: [ "propuesta", "en progreso", "terminado"]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  http_basic_authenticate_with name: 'desafiovamoscontodo',
  password: 'XAHTJEAS23123%23', except: [:dashboard]

  def dashboard
    if params[:filter_by].nil? || params[:filter_by].empty?
      @projects = Project.all
    else
      @projects = Project.where(state: params[:filter_by])
    end

  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.create( project_params )
    if @project.valid?
      @project.save
      redirect_to root_path, notice: "Se guardo el proyecto correctamente"
    else
      redirect_to root_path, notice: "No se pudo guardar el proyecto"
    end

  end

  private
  def project_params
    params.require( :project ).permit(:name, :description, :begin, :end, :state)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GestorDeProyectos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/create.html.erb
<h1>Projects#create</h1>

app/views/projects/dashboard.html.erb
<h1>Projects</h1>

<% if notice%>
    <div style="color: white; background-color: black; paddding:10px"><%= notice %></div>
<%end%>

<div>
    <%= link_to "Crear nuevo", projects_new_path %>
    <div style="float: right">
        <label>Seleccione estado: </label>
        <%= link_to "Todos", root_path%>
        <%= link_to "Propuesta", list_filtered_path("propuesta")%>
        <%= link_to "En progreso", list_filtered_path("en progreso")%>
        <%= link_to "Terminado", list_filtered_path("terminado")%>
    </div>
</div>
<br/>
<table style="width:100%">
    <tr>
        <th>Nombre</th>
        <th>Descripción</th>
        <th>Inicio</th>
        <th>Termino</th>
        <th>Estado</th>
    </tr>

    <% @projects.each do |project| %>
    <tr>
        <td><%= project.name %></td>
        <td><%= project.description %></td>
        <td><%= project.begin %></td>
        <td><%= project.end %></td>
        <td><%= project.state %></td>
    </tr>
    <% end %>

</table>

app/views/projects/new.html.erb
<h1>Projects#new</h1>

<div>
<%= link_to "Volver", root_path %>
</div>

<hr/>

<%= form_with(model: @project, local: true) do |form| %>
    <div class="form-group">
        <%= form.label :name %>
        <br/>
        <%= form.text_field :name %>
    </div>

    <div class="form-group">
        <%= form.label :description %>
        <br/>
        <%= form.text_area :description %>
    </div>

        <div class="form-group">
        <%= form.label :begin %>
        <br/>
        <%= form.date_field :begin %>
    </div>

        <div class="form-group">
        <%= form.label :end %>
        <br/>
        <%= form.date_field :end %>
    </div>
 
      <div class="form-group">
        <%= form.label :state %>
        <br/>
        <%= form.select :state, Project.states.keys %> 
    </div>

    <div class="actions">
        <br/>
        <%= form.submit %>
    </div>
<% end %>